# Generated by Django 4.0.4 on 2022-04-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_opening', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Companie',
        ),
    ]
