# Generated by Django 4.0.4 on 2022-04-30 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_opening', '0002_rename_companies_companie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companie',
            name='id',
        ),
        migrations.AddField(
            model_name='companie',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companie',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companie',
            name='r_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companie',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
