# Generated by Django 4.0.4 on 2022-04-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_opening', '0003_remove_companie_id_companie_email_companie_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companie',
            old_name='password',
            new_name='salt',
        ),
        migrations.RemoveField(
            model_name='companie',
            name='r_password',
        ),
    ]
