# Generated by Django 4.0.4 on 2022-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_opening', '0004_rename_password_companie_salt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewJob',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('jobRole', models.CharField(max_length=100)),
                ('jobDesc', models.CharField(max_length=1000)),
                ('place', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
