# Generated by Django 4.0.4 on 2022-05-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_opening', '0005_newjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companie',
        ),
    ]
